name: frame_realtime_gemini_voicevision
description: "Connects to Frame, streams audio from the Frame microphone and photos from its camera in a websockets conversation with the Gemini Realtime API"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.32.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  logging: ^1.3.0
  simple_frame_app: ^7.1.0
  frame_msg: ^2.0.0
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  flutter_foreground_task: ^9.1.0
  flutter_pcm_sound: ^3.1.7
  web_socket_channel: ^3.0.3

  # ObjectBox dependencies
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0

  # Path packages
  path_provider: ^2.1.5
  path: ^1.9.1

  # NEW: Added for Phase 1
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ObjectBox generator dependencies
  build_runner: ^2.5.0
  objectbox_generator: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/camera.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - assets/frame_app.min.lua
