name: cognitive_assistant
description: "A Flutter-based cognitive augmentation assistant for Brilliant Labs Frame."
publish_to: 'none'
version: 1.0.0+1

environment:
  # This correctly reflects your modern local environment
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Latest stable versions of all key packages
  simple_frame_app: ^7.1.0
  frame_msg:        ^2.0.0
  flutter_blue_plus: ^1.35.5
  tflite_flutter:            ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  objectbox:              ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  shared_preferences:      ^2.5.3
  share_plus:              ^11.0.0
  flutter_foreground_task: ^9.1.0
  flutter_pcm_sound:       ^3.1.7
  web_socket_channel:      ^3.0.3
  path_provider:           ^2.1.5
  path:                    ^1.9.1
  uuid:                    ^4.5.1
  rxdart:                  ^0.28.0
  logging:                 ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:   ^6.0.0
  build_runner:    ^2.4.15
  objectbox_generator: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilebert_embedding.tflite
    - assets/models/vocab.txt
