name: frame_realtime_gemini_voicevision
description: >
  Connects to Frame, streams audio from the Frame microphone and photos from its
  camera in a WebSocket conversation with the Gemini Realtime API.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth stack (BLE only)
  flutter_blue_plus: ^1.32.12

  # Frame SDK
  simple_frame_app: ^7.0.0
  frame_msg: ^2.0.0

  # Core utilities
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  share_plus: ^11.0.0               # v2-ready
  permission_handler: ^11.3.1

  # Real-time pipeline
  flutter_pcm_sound: ^3.1.7         # latest stable, v2-ready
  web_socket_channel: ^2.4.0

  # Foreground service (v2 embedding)
  flutter_foreground_task: ^9.1.0

  # ML Kit (v2 embedding)
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0

  # ObjectBox
  objectbox: ^4.0.0
  objectbox_flutter_libs: any

  # Misc
  path_provider: ^2.1.3
  path: ^1.9.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  objectbox_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/camera.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - assets/frame_app.min.lua
