name: Build Cognitive Assistant APK

on:
  push:
    branches:
      - refactor-v2        # watches your working branch
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Demo APK
    runs-on: ubuntu-latest

    steps:
      # ─────────── Checkout ──────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4

      # ─────────── JDK 17 (for Gradle 8+) ────────────────────────────────
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ─────────── Flutter SDK 3.32.5 (Dart 3.8.1) ───────────────────────
      - name: Set up Flutter 3.32.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.5       # exact tag
          channel: stable               # ignored because tag given
          cache: true                   # cache SDK + pub-cache

      - name: Show tool versions
        run: flutter --version

      # ─────────── Dependencies & code-gen ───────────────────────────────
      - name: flutter pub get
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # ─────────── Lint gate (fails build on new errors) ─────────────────
      - name: Static analysis
        run: flutter analyze --no-pub

      # ─────────── Build APK with verbose log capture ────────────────────
      - name: flutter clean
        run: flutter clean

      - name: Build Debug APK (capture log)
        id: build_apk
        run: |
          # Capture full verbose output for troubleshooting
          set -o pipefail
          flutter build apk --debug -v 2>&1 | tee flutter-build.log

      # ─────────── Upload build log always (success or fail) ─────────────
      - name: Upload flutter-build.log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-log
          path: flutter-build.log

      # ─────────── Upload APK only on success ────────────────────────────
      - name: Upload Debug APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cognitive-assistant-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
