name: Build Frame Vision Gemini Demo APK

on:
  push:
    branches:
      - temp-stable-build
  pull_request:
    branches:
      - temp-stable-build
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Demo APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # CORRECTED based on your research to get a compatible Dart SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Ensure gradlew is executable
        run: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          else
            echo "android/gradlew not found, skipping chmod. Flutter build will attempt to proceed."
          fi

      - name: Clean Flutter build cache
        run: flutter clean

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Demo APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frame-vision-gemini-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
