name: Build Cognitive Assistant APK

on:
  push:
    branches:
      - refactor-v2        # watches your new branch
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Demo APK
    runs-on: ubuntu-latest

    steps:
      # ─────────── Checkout ──────────────────────────────────────────────
      - name: Checkout repository code
        uses: actions/checkout@v4

      # ─────────── JDK 17 (Gradle 8+) ────────────────────────────────────
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ─────────── Flutter SDK 3.32.5 (Dart 3.8.1) ───────────────────────
      - name: Set up Flutter 3.32.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"   # tag you tested locally
          channel: stable             # ignored when tag is explicit
          cache: true                 # caches ~/.pub-cache & SDK

      - name: Confirm toolchain
        run: flutter --version

      # ─────────── Dependencies & code-gen ───────────────────────────────
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # ─────────── Lint gate (optional) ──────────────────────────────────
      - name: Static analysis
        run: flutter analyze --no-pub

      # ─────────── Build APK ─────────────────────────────────────────────
      - name: Clean Flutter build cache
        run: flutter clean

      - name: Build Debug APK
        run: flutter build apk --debug -v

      # ─────────── Upload artifact ───────────────────────────────────────
      - name: Upload Demo APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cognitive-assistant-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
