name: Build Cognitive Assistant APK

# Controls when the workflow will run
on:
  push:
    branches:
      - final-working-code # This now watches our new, clean branch
      - main
      - temp-stable-build
  pull_request:
    branches:
      - main
      - temp-stable-build
  workflow_dispatch: # Allows you to trigger this workflow manually

jobs:
  build_apk:
    name: Build Demo APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Set up Java Development Kit (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set up Flutter SDK (Corrected to use latest stable version)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'
          cache: true

      # ADDED: This step helps verify the environment in the build logs
      - name: Verify Flutter Version
        run: flutter --version

      # 4. Install Flutter project dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # 5. Generate database code (Required for ObjectBox)
      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs
        
      # 6. Clean the project before building
      - name: Clean Flutter build cache
        run: flutter clean

      # 7. Build the debug APK
      - name: Build Debug APK
        run: flutter build apk --debug

      # 8. Upload the generated APK as an artifact
      - name: Upload Demo APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cognitive-assistant-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error