name: Build Cognitive Assistant APK

on:
  push:
    branches:
      - refactor-v2  # This now watches our new branch
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Demo APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Clean Flutter build cache
        run: flutter clean

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Demo APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cognitive-assistant-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error