name: Flutter CI - Test Pipeline

# 1. TRIGGER: When the pipeline should run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Flutter Analyzer & Tests
    runs-on: ubuntu-latest

    steps:
      # 2. SETUP ENVIRONMENT: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SETUP ENVIRONMENT: Setup Flutter (Matches build-demo-apk.yml)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Uses the latest stable Flutter SDK, same as your build workflow
          cache: true

      # (Optional) 2. SETUP ENVIRONMENT: Setup Java
      # Your build_demo_apk.yml uses Java 17. Adding it here for consistency if any
      # test-related tools or future steps might need it.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. DEPENDENCIES: Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # 4. STATIC ANALYSIS: Check formatting
      - name: Check Dart formatting
        run: flutter format --output=none --set-exit-if-changed .

      # 4. STATIC ANALYSIS: Analyze Dart code
      - name: Analyze Dart code
        run: flutter analyze

      # 5. TESTING: Run Flutter tests
      - name: Run Flutter tests
        run: flutter test

      # ... (Optional integration tests, build steps, artifacts as before) ...
